In [213]:
import pandas as pd
import numpy as np

In [214]:
df = pd.read_csv('houseprice.csv')

In [275]:
df.head(5)

MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  1stFlrSF  \
0           5         3         65.0     8450       1         3       856   
1           0         3         80.0     9600       1         3      1262   
2           5         3         68.0    11250       1         0       920   
3           6         3         60.0     9550       1         0       961   
4           5         3         84.0    14260       1         0      1145   

   2ndFlrSF  SalePrice  Total Years  
0       854     208500           22  
1         0     181500           49  
2       866     223500           24  
3       756     140000          110  
4      1053     250000           25

In [276]:
df=pd.read_csv('houseprice.csv',usecols=["SalePrice", "MSSubClass", "MSZoning", "LotFrontage", "LotArea",
                                         "Street", "YearBuilt", "LotShape", "1stFlrSF", "2ndFlrSF"]).dropna()

In [277]:
df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street LotShape  YearBuilt  \
0          60       RL         65.0     8450   Pave      Reg       2003   
1          20       RL         80.0     9600   Pave      Reg       1976   
2          60       RL         68.0    11250   Pave      IR1       2001   
3          70       RL         60.0     9550   Pave      IR1       1915   
4          60       RL         84.0    14260   Pave      IR1       2000   

   1stFlrSF  2ndFlrSF  SalePrice  
0       856       854     208500  
1      1262         0     181500  
2       920       866     223500  
3       961       756     140000  
4      1145      1053     250000

In [278]:
df.shape

(1201, 10)

In [279]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1201 non-null   int64  
 1   MSZoning     1201 non-null   object 
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64  
 4   Street       1201 non-null   object 
 5   LotShape     1201 non-null   object 
 6   YearBuilt    1201 non-null   int64  
 7   1stFlrSF     1201 non-null   int64  
 8   2ndFlrSF     1201 non-null   int64  
 9   SalePrice    1201 non-null   int64  
dtypes: float64(1), int64(6), object(3)
memory usage: 103.2+ KB


In [280]:
for i in df.columns:
    print("Column name {} and unique values are {}".format(i,len(df[i].unique())))

Column name MSSubClass and unique values are 15
Column name MSZoning and unique values are 5
Column name LotFrontage and unique values are 110
Column name LotArea and unique values are 869
Column name Street and unique values are 2
Column name LotShape and unique values are 4
Column name YearBuilt and unique values are 112
Column name 1stFlrSF and unique values are 678
Column name 2ndFlrSF and unique values are 368
Column name SalePrice and unique values are 597


In [281]:
import datetime
datetime.datetime.now().year

2025

In [282]:
df['Total Years']=datetime.datetime.now().year-df['YearBuilt']

In [283]:
df.drop("YearBuilt",axis=1,inplace=True)

In [284]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', '1stFlrSF', '2ndFlrSF', 'SalePrice', 'Total Years'],
      dtype='object')

In [285]:
cat_features=["MSSubClass", "MSZoning", "Street", "LotShape"]
out_feature="SalePrice"

In [286]:
from sklearn.preprocessing import LabelEncoder
lbl_encoders={}
lbl_encoders["MSSubClass"]=LabelEncoder()
lbl_encoders["MSSubClass"].fit_transform(df["MSSubClass"])

array([5, 0, 5, ..., 6, 0, 0], dtype=int64)

In [287]:
lbl_encoders

{'MSSubClass': LabelEncoder()}

In [288]:
from sklearn.preprocessing import LabelEncoder
lbl_encoders={}
for feature in cat_features:
    lbl_encoders[feature]=LabelEncoder()
    df[feature]=lbl_encoders[feature].fit_transform(df[feature])

In [289]:
df

MSSubClass  MSZoning  LotFrontage  LotArea  Street  LotShape  1stFlrSF  \
0              5         3         65.0     8450       1         3       856   
1              0         3         80.0     9600       1         3      1262   
2              5         3         68.0    11250       1         0       920   
3              6         3         60.0     9550       1         0       961   
4              5         3         84.0    14260       1         0      1145   
...          ...       ...          ...      ...     ...       ...       ...   
1455           5         3         62.0     7917       1         3       953   
1456           0         3         85.0    13175       1         3      2073   
1457           6         3         66.0     9042       1         3      1188   
1458           0         3         68.0     9717       1         3      1078   
1459           0         3         75.0     9937       1         3      1256   

      2ndFlrSF  SalePrice  Total Years  
0          854     208500           22  
1            0     181500           49  
2          866     223500           24  
3          756     140000          110  
4         1053     250000           25  
...        ...        ...          ...  
1455       694     175000           26  
1456         0     210000           47  
1457      1152     266500           84  
1458         0     142125           75  
1459         0     147500           60  

[1201 rows x 10 columns]

In [290]:
### Stacking and Converting Into Tensors
cat_features=np.stack([df['MSSubClass'],df['MSZoning'],df['Street'],df['LotShape']],1)
cat_features

array([[5, 3, 1, 3],
       [0, 3, 1, 3],
       [5, 3, 1, 0],
       ...,
       [6, 3, 1, 3],
       [0, 3, 1, 3],
       [0, 3, 1, 3]], dtype=int64)

In [291]:
%pip install torch

Note: you may need to restart the kernel to use updated packages.


In [292]:
### Convert numpy to Tensors
import torch
cat_features=torch.tensor(cat_features,dtype=torch.int64)
cat_features

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [293]:
#### create continuous variable
cont_features=[]
for i in df.columns:
    if i in ["MSSubClass", "MSZoning", "Street", "LotShape","SalePrice"]:
        pass
    else:
        cont_features.append(i)

In [294]:
cont_features

['LotFrontage', 'LotArea', '1stFlrSF', '2ndFlrSF', 'Total Years']

In [295]:
### Stacking continuous variable to a tensor
cont_values=np.stack([df[i].values for i in cont_features],axis=1)
cont_values=torch.tensor(cont_values,dtype=torch.float)
cont_values

tensor([[   65.,  8450.,   856.,   854.,    22.],
        [   80.,  9600.,  1262.,     0.,    49.],
        [   68., 11250.,   920.,   866.,    24.],
        ...,
        [   66.,  9042.,  1188.,  1152.,    84.],
        [   68.,  9717.,  1078.,     0.,    75.],
        [   75.,  9937.,  1256.,     0.,    60.]])

In [296]:
cont_values.dtype

torch.float32

In [297]:
### Dependent Feature 
y=torch.tensor(df['SalePrice'].values,dtype=torch.float).reshape(-1,1)
y

tensor([[208500.],
        [181500.],
        [223500.],
        ...,
        [266500.],
        [142125.],
        [147500.]])

In [298]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   MSSubClass   1201 non-null   int64  
 1   MSZoning     1201 non-null   int32  
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64  
 4   Street       1201 non-null   int32  
 5   LotShape     1201 non-null   int32  
 6   1stFlrSF     1201 non-null   int64  
 7   2ndFlrSF     1201 non-null   int64  
 8   SalePrice    1201 non-null   int64  
 9   Total Years  1201 non-null   int64  
dtypes: float64(1), int32(3), int64(6)
memory usage: 89.1 KB


In [299]:
cat_features.shape,cont_values.shape,y.shape

(torch.Size([1201, 4]), torch.Size([1201, 5]), torch.Size([1201, 1]))

In [300]:
len(df['MSSubClass'].unique())

15

In [301]:
#### Embedding Size For Categorical columns
cat_dims=[len(df[col].unique()) for col in ["MSSubClass", "MSZoning", "Street", "LotShape"]]

In [302]:
cat_dims

[15, 5, 2, 4]

In [303]:
embedding_dim= [(x, min(50, (x + 1) // 2)) for x in cat_dims]

In [304]:
embedding_dim

[(15, 8), (5, 3), (2, 1), (4, 2)]

In [305]:
import torch
import torch.nn as nn
import torch.nn.functional as F
embed_representation=nn.ModuleList([nn.Embedding(inp,out) for inp,out in embedding_dim])
embed_representation

ModuleList(
  (0): Embedding(15, 8)
  (1): Embedding(5, 3)
  (2): Embedding(2, 1)
  (3): Embedding(4, 2)
)

In [306]:
cat_features

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [307]:
cat_featuresz=cat_features[:4]
cat_featuresz

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        [6, 3, 1, 0]])

In [308]:
pd.set_option('display.max_rows', 500)
embedding_val=[]
for i,e in enumerate(embed_representation):
    embedding_val.append(e(cat_features[:,i]))

In [309]:
embedding_val

[tensor([[ 0.1160, -0.5836,  0.1142,  ...,  1.0497, -0.1206, -1.8167],
         [-0.8677, -1.3736,  0.3053,  ..., -0.6119, -0.8595,  0.8906],
         [ 0.1160, -0.5836,  0.1142,  ...,  1.0497, -0.1206, -1.8167],
         ...,
         [ 1.2494,  0.4159,  1.7399,  ...,  1.5180,  1.6180, -0.8075],
         [-0.8677, -1.3736,  0.3053,  ..., -0.6119, -0.8595,  0.8906],
         [-0.8677, -1.3736,  0.3053,  ..., -0.6119, -0.8595,  0.8906]],
        grad_fn=<EmbeddingBackward0>),
 tensor([[-1.3654,  0.4189, -0.7423],
         [-1.3654,  0.4189, -0.7423],
         [-1.3654,  0.4189, -0.7423],
         ...,
         [-1.3654,  0.4189, -0.7423],
         [-1.3654,  0.4189, -0.7423],
         [-1.3654,  0.4189, -0.7423]], grad_fn=<EmbeddingBackward0>),
 tensor([[-2.0546],
         [-2.0546],
         [-2.0546],
         ...,
         [-2.0546],
         [-2.0546],
         [-2.0546]], grad_fn=<EmbeddingBackward0>),
 tensor([[0.8648, 0.6523],
         [0.8648, 0.6523],
         [0.6751, 0.8799],

In [310]:
z = torch.cat(embedding_val, 1)
z

tensor([[ 0.1160, -0.5836,  0.1142,  ..., -2.0546,  0.8648,  0.6523],
        [-0.8677, -1.3736,  0.3053,  ..., -2.0546,  0.8648,  0.6523],
        [ 0.1160, -0.5836,  0.1142,  ..., -2.0546,  0.6751,  0.8799],
        ...,
        [ 1.2494,  0.4159,  1.7399,  ..., -2.0546,  0.8648,  0.6523],
        [-0.8677, -1.3736,  0.3053,  ..., -2.0546,  0.8648,  0.6523],
        [-0.8677, -1.3736,  0.3053,  ..., -2.0546,  0.8648,  0.6523]],
       grad_fn=<CatBackward0>)

In [311]:
#### Implement dropupout
droput=nn.Dropout(.4)

In [312]:
final_embed=droput(z)
final_embed

tensor([[ 0.0000, -0.0000,  0.1903,  ..., -3.4244,  0.0000,  1.0871],
        [-0.0000, -0.0000,  0.5088,  ..., -3.4244,  1.4413,  1.0871],
        [ 0.0000, -0.9726,  0.0000,  ..., -3.4244,  1.1252,  0.0000],
        ...,
        [ 2.0824,  0.6931,  2.8998,  ..., -0.0000,  1.4413,  1.0871],
        [-1.4462, -2.2894,  0.5088,  ..., -3.4244,  0.0000,  0.0000],
        [-1.4462, -2.2894,  0.5088,  ..., -0.0000,  0.0000,  1.0871]],
       grad_fn=<MulBackward0>)

In [313]:
##### Create a Feed Forward Neural Network
import torch
import torch.nn as nn
import torch.nn.functional as F
class FeedForwardNN(nn.Module):

    def __init__(self, embedding_dim, n_cont, out_sz, layers, p=0.5):
        super().__init__()
        self.embeds = nn.ModuleList([nn.Embedding(inp,out) for inp,out in embedding_dim])
        self.emb_drop = nn.Dropout(p)
        self.bn_cont = nn.BatchNorm1d(n_cont)
        
        layerlist = []
        n_emb = sum((out for inp,out in embedding_dim))
        n_in = n_emb + n_cont
        
        for i in layers:
            layerlist.append(nn.Linear(n_in,i)) 
            layerlist.append(nn.ReLU(inplace=True))
            layerlist.append(nn.BatchNorm1d(i))
            layerlist.append(nn.Dropout(p))
            n_in = i
        layerlist.append(nn.Linear(layers[-1],out_sz))
            
        self.layers = nn.Sequential(*layerlist)
    def forward(self, x_cat, x_cont):
        embeddings = []
        for i,e in enumerate(self.embeds):
            embeddings.append(e(x_cat[:,i]))
        x = torch.cat(embeddings, 1)
        x = self.emb_drop(x)
        
        x_cont = self.bn_cont(x_cont)
        x = torch.cat([x, x_cont], 1)
        x = self.layers(x)
        return x

In [314]:
len(cont_features)

5

In [315]:
torch.manual_seed(100)
model=FeedForwardNN(embedding_dim,len(cont_features),1,[100,50],p=0.4)

In [316]:
model

FeedForwardNN(
  (embeds): ModuleList(
    (0): Embedding(15, 8)
    (1): Embedding(5, 3)
    (2): Embedding(2, 1)
    (3): Embedding(4, 2)
  )
  (emb_drop): Dropout(p=0.4, inplace=False)
  (bn_cont): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=19, out_features=100, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=100, out_features=50, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=50, out_features=1, bias=True)
  )
)

Define Loss And Optimizer

In [317]:
loss_function=nn.MSELoss()
optimizer=torch.optim.Adam(model.parameters(),lr=0.01)

In [318]:
df.shape

(1201, 10)

In [319]:
cont_values.shape

torch.Size([1201, 5])

In [320]:
batch_size=1200
test_size=int(batch_size*0.15)
train_categorical=cat_features[:batch_size-test_size]
test_categorical=cat_features[batch_size-test_size:batch_size]
train_cont=cont_values[:batch_size-test_size]
test_cont=cont_values[batch_size-test_size:batch_size]
y_train=y[:batch_size-test_size]
y_test=y[batch_size-test_size:batch_size]

In [321]:
len(train_categorical),len(test_categorical),len(train_cont),len(test_cont),len(y_train),len(y_test)

(1020, 180, 1020, 180, 1020, 180)

In [322]:
epochs=5000
final_losses=[]
for i in range(epochs):
    i=i+1
    y_pred=model(train_categorical,train_cont)
    loss=torch.sqrt(loss_function(y_pred,y_train)) ### RMSE
    final_losses.append(loss.item())
    if i%10==1:
        print("Epoch number: {} and the loss : {}".format(i,loss.item()))
    optimizer.zero_grad()
    loss.backward()## back propogation
    optimizer.step()

Epoch number: 1 and the loss : 200496.75
Epoch number: 11 and the loss : 200493.46875
Epoch number: 21 and the loss : 200489.140625
Epoch number: 31 and the loss : 200482.640625
Epoch number: 41 and the loss : 200473.25
Epoch number: 51 and the loss : 200461.375
Epoch number: 61 and the loss : 200446.4375
Epoch number: 71 and the loss : 200429.390625
Epoch number: 81 and the loss : 200407.96875
Epoch number: 91 and the loss : 200383.390625
Epoch number: 101 and the loss : 200355.296875
Epoch number: 111 and the loss : 200322.03125
Epoch number: 121 and the loss : 200291.34375
Epoch number: 131 and the loss : 200252.15625
Epoch number: 141 and the loss : 200206.625
Epoch number: 151 and the loss : 200161.546875
Epoch number: 161 and the loss : 200112.234375
Epoch number: 171 and the loss : 200059.828125
Epoch number: 181 and the loss : 200006.3125
Epoch number: 191 and the loss : 199946.484375
Epoch number: 201 and the loss : 199881.8125
Epoch number: 211 and the loss : 199815.9375
Epoc

In [323]:
import matplotlib.pyplot as plt
%matplotlib inline

In [264]:
plt.plot(range(epochs), final_losses)
plt.ylabel('RMSE Loss')
plt.xlabel('epoch')
plt.show()

In [324]:
#### Validate the Test Data
y_pred=""
with torch.no_grad():
    y_pred=model(test_categorical,test_cont)
    loss=torch.sqrt(loss_function(y_pred,y_test))
print('RMSE: {}'.format(loss))

RMSE: 42027.74609375


In [325]:
data_verify=pd.DataFrame(y_test.tolist(),columns=["Test"])

In [326]:
data_predicted=pd.DataFrame(y_pred.tolist(),columns=["Prediction"])

In [327]:
data_predicted

Prediction
0    144513.906250
1    194738.156250
2    162013.484375
3    231717.281250
4    222526.437500
5    189436.953125
6    151732.093750
7    295857.906250
8    141325.968750
9    392116.281250
10   197533.796875
11   187342.343750
12   182752.781250
13   107637.398438
14   212710.296875
15   115164.453125
16   230242.328125
17   112627.867188
18   318012.156250
19    81091.664062
20   189465.093750
21   104743.179688
22    94940.960938
23   188382.437500
24   191119.625000
25   185546.468750
26   125808.945312
27   352200.125000
28   145707.125000
29   150395.593750
30    66219.804688
31   126751.382812
32   267355.968750
33    93464.992188
34   235277.375000
35   197043.343750
36   120238.257812
37   132327.640625
38   160769.296875
39   105660.648438
40   256967.890625
41   312361.718750
42    78571.726562
43   149448.750000
44   200339.843750
45    98057.992188
46   100948.664062
47   139487.906250
48   143162.156250
49   307217.531250
50   138679.468750
51   347674.656250
52   231546.671875
53   138634.812500
54   246401.843750
55   206628.343750
56   123174.289062
57   120270.671875
58   269327.500000
59   170819.609375
60   335044.406250
61   105263.585938
62   226274.500000
63   232180.187500
64   165745.343750
65   123509.468750
66   158677.171875
67   265920.250000
68    75791.273438
69   255304.359375
70    86222.039062
71    79401.164062
72    94721.867188
73   280095.562500
74   198294.750000
75   233026.328125
76   133762.093750
77    94519.351562
78   115871.648438
79   112229.390625
80   136614.687500
81   127175.945312
82    91161.062500
83   261792.703125
84   122893.242188
85   104984.062500
86   151978.562500
87   131334.906250
88   145517.718750
89    94572.867188
90   282915.593750
91   108832.539062
92   166318.218750
93   134693.875000
94   125397.460938
95   434020.375000
96   203265.312500
97   395792.875000
98   278171.500000
99   265853.406250
100  167520.250000
101  169696.390625
102  218566.218750
103  103464.085938
104  266899.750000
105  139257.312500
106  176640.875000
107  238139.031250
108  271586.343750
109  244433.796875
110   94589.523438
111  125462.953125
112   46060.812500
113  207086.812500
114  117138.101562
115  142923.781250
116  127590.398438
117  103704.976562
118  358993.375000
119  308076.593750
120  260388.531250
121  106255.140625
122  160514.531250
123  106875.992188
124  107631.820312
125  127241.851562
126  214560.687500
127  446671.218750
128   94842.335938
129  152705.921875
130  110820.335938
131  121674.703125
132  189508.812500
133  181490.281250
134  234996.812500
135   95992.781250
136  246109.687500
137  118667.023438
138  130164.679688
139  219436.406250
140  232307.812500
141  152968.546875
142   86238.781250
143  329216.218750
144  143950.687500
145  260358.687500
146  127804.468750
147  128023.328125
148  140829.250000
149  129887.484375
150  112353.648438
151  128496.320312
152  219138.687500
153  134702.921875
154  103631.164062
155  221315.531250
156   97381.453125
157  182028.593750
158  160456.625000
159  169793.375000
160  117604.335938
161  320583.156250
162  127573.765625
163  196460.906250
164  217824.968750
165  355125.281250
166  209383.453125
167   94057.851562
168  262573.906250
169  105079.406250
170   94073.031250
171  104659.156250
172  295900.781250
173  100973.289062
174  159539.781250
175  167995.875000
176  178968.500000
177  267484.812500
178  227580.359375
179  111340.539062

In [328]:
final_output=pd.concat([data_verify,data_predicted],axis=1)
final_output['Difference']=final_output['Test']-final_output['Prediction']
final_output.head(10)

Test     Prediction    Difference
0  130000.0  144513.906250 -14513.906250
1  138887.0  194738.156250 -55851.156250
2  175500.0  162013.484375  13486.515625
3  195000.0  231717.281250 -36717.281250
4  142500.0  222526.437500 -80026.437500
5  265900.0  189436.953125  76463.046875
6  224900.0  151732.093750  73167.906250
7  248328.0  295857.906250 -47529.906250
8  170000.0  141325.968750  28674.031250
9  465000.0  392116.281250  72883.718750

In [329]:
#### Save the model
torch.save(model,'HousePrice.pt')

In [330]:
torch.save(model.state_dict(),'HouseWeights.pt')

In [331]:
### Loading the saved Model
embs_size=[(15, 8), (5, 3), (2, 1), (4, 2)]
model1=FeedForwardNN(embs_size,5,1,[100,50],p=0.4)

In [332]:
model1.load_state_dict(torch.load('HouseWeights.pt'))

<All keys matched successfully>

In [333]:
model1.eval()

FeedForwardNN(
  (embeds): ModuleList(
    (0): Embedding(15, 8)
    (1): Embedding(5, 3)
    (2): Embedding(2, 1)
    (3): Embedding(4, 2)
  )
  (emb_drop): Dropout(p=0.4, inplace=False)
  (bn_cont): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=19, out_features=100, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=100, out_features=50, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=50, out_features=1, bias=True)
  )
)